export const GAME_START = 'GAME_START'
export const GAME_FINISH = 'GAME_FINISH'

export const GAME_INIT = 'GAME_INIT'
export const GAME_PLAY = 'GAME_PLAY'
export const GAME_START_FRAME = 'GAME_START_FRAME'
export const GAME_FINISH_FRAME = 'GAME_FINISH_FRAME'

export const GAME_PLAYED_STRIKE = 'GAME_PLAYED_STRIKE'
export const GAME_PLAYED_SPARE = 'GAME_PLAYED_SPARE'

export const GAME_ADD_PLAYER = 'GAME_ADD_PLAYER'

export const GAME_THROW_BALL = 'GAME_THROW_BALL'
export const GAME_BALL_ROLLING = 'GAME_BALL_ROLLING'
export const GAME_BALL_REACHED = 'GAME_BALL_REACHED'
